"""PrizePicks team abbreviation → canonical school name (shared by step3b/3c)."""

from __future__ import annotations

ABBR_TO_SR: dict[str, str] = {
    "ALA": "Alabama",
    "ARK": "Arkansas",
    "BC": "Boston College",
    "BUT": "Butler",
    "CAL": "California",
    "COLO": "Colorado",
    "CONN": "Connecticut",
    "CREI": "Creighton",
    "DEP": "DePaul",
    "FLA": "Florida",
    "GC": "Grand Canyon",
    "GMU": "George Mason",
    "GONZ": "Gonzaga",
    "IOWA": "Iowa",
    "JOES": "Saint Joseph's",
    "KSU": "Kansas State",
    "LSU": "Louisiana State",
    "MD": "Maryland",
    "MISS": "Mississippi",
    "MSST": "Mississippi State",
    "MSU": "Michigan State",
    "NEB": "Nebraska",
    "ORE": "Oregon",
    "ORST": "Oregon State",
    "OSU": "Ohio State",
    "PEPP": "Pepperdine",
    "PITT": "Pittsburgh",
    "PORT": "Portland",
    "PROV": "Providence",
    "PUR": "Purdue",
    "SCU": "Santa Clara",
    "SDSU": "San Diego State",
    "SEA": "Seattle",
    "SJU": "St. John's (NY)",
    "SMC": "Saint Mary's (CA)",
    "SMU": "Southern Methodist",
    "STAN": "Stanford",
    "TEX": "Texas",
    "TXAM": "Texas A&M",
    "UGA": "Georgia",
    "UNLV": "Nevada-Las Vegas",
    "USD": "San Diego",
    "USU": "Utah State",
    "VAN": "Vanderbilt",
    "VILL": "Villanova",
    "WAKE": "Wake Forest",
    "WIS": "Wisconsin",
    "XAV": "Xavier",
    "UK": "Kentucky",
    "UNC": "North Carolina",
    "KU": "Kansas",
    "IU": "Indiana",
    "OU": "Oklahoma",
    "UVA": "Virginia",
    "USC": "Southern California",
    "UCLA": "UCLA",
    "DUKE": "Duke",
    "SYR": "Syracuse",
    "MARQ": "Marquette",
    "NOVA": "Villanova",
    "UT": "Utah",
    "MICH": "Michigan",
    "PSU": "Penn State",
    "MSS": "Mississippi State",
    "RUTG": "Rutgers",
    "NW": "Northwestern",
    "MN": "Minnesota",
    "ILL": "Illinois",
    "FAU": "Florida Atlantic",
    "WICH": "Wichita State",
    "TEM": "Temple",
    "MEM": "Memphis",
    "BRY": "Bryant",
    "UMBC": "Maryland-Baltimore County",
    "AFA": "Air Force",
    "AKR": "Akron",
    "APP": "Appalachian State",
    "ARIZ": "Arizona",
    "ARST": "Arizona State",
    "ASU": "Arizona State",
    "AUB": "Auburn",
    "BALL": "Ball State",
    "BAY": "Baylor",
    "BELM": "Belmont",
    "BGSU": "Bowling Green",
    "BRAD": "Bradley",
    "BYU": "Brigham Young",
    "BUFF": "Buffalo",
    "CHAR": "Charlotte",
    "CIN": "Cincinnati",
    "CLEM": "Clemson",
    "CLT": "Charlotte",
    "COLST": "Colorado State",
    "DAV": "Davidson",
    "DAY": "Dayton",
    "DRK": "Drake",
    "DRX": "Drexel",
    "DUQ": "Duquesne",
    "ECU": "East Carolina",
    "ETSU": "East Tennessee State",
    "FLST": "Florida State",
    "FOR": "Fordham",
    "FRES": "Fresno State",
    "FUR": "Furman",
    "GTWN": "Georgetown",
    "GASO": "Georgia Southern",
    "GAST": "Georgia State",
    "GT": "Georgia Tech",
    "HAW": "Hawaii",
    "HOU": "Houston",
    "IDHO": "Idaho",
    "ILST": "Illinois State",
    "INST": "Indiana State",
    "TLSA": "Tulsa",
    "TCU": "TCU",
    "TTU": "Texas Tech",
    "UAB": "UAB",
    "UCF": "UCF",
    "UCONN": "Connecticut",
    "URI": "Rhode Island",
    "VCU": "VCU",
    "VT": "Virginia Tech",
    "WVU": "West Virginia",
    "ZAG": "Gonzaga",
}
