#requires -Version 5.1
<#
.SYNOPSIS
  Shared pre-pull repair for scheduled PropOracle wrappers (5AM / 8AM).

.DESCRIPTION
  Early runs were aborting with exit 128 whenever main_cp had unmerged index
  entries on published JSON (tickets_latest, pipeline_status, sport_breakdown).
  Those files are regenerated by the daily/refresh — they must never block a run.

  This script:
    1) Aborts leftover merge/rebase/cherry-pick when safe
    2) Clears orphaned unmerged entries on known generated publish paths
    3) Optionally stashes WIP, ff-only pulls, stash-pops
    4) On pull failure: continues with local tree (same policy as run_payout_cdp)
    5) On stash-pop conflicts limited to generated paths: resets them and continues

.PARAMETER RepoRoot
  Git worktree root (defaults to current location).

.PARAMETER Label
  Log prefix, e.g. "[5AM DAILY]".

.PARAMETER SkipPull
  Only repair unmerged state; do not stash/pull.

.PARAMETER AbortOnPullFail
  If set, non-zero pull exit aborts (legacy). Default is to continue with local tree.

.OUTPUTS
  Exit code 0 = safe to run daily (pull may have been skipped/failed).
  Exit code 2 = real source-code unmerged conflict remains (caller should abort).
#>
param(
    [string]$RepoRoot = "",
    [string]$Label = "[PULL]",
    [switch]$SkipPull,
    # Default: continue scheduled run if pull fails (same as payout CDP).
    # Pass -AbortOnPullFail to restore old hard-fail behavior.
    [switch]$AbortOnPullFail,
    [string]$StashMessage = ""
)

$ErrorActionPreference = "Continue"
$ContinueOnPullFail = -not $AbortOnPullFail.IsPresent

# Published / regenerated by pipeline + STEP E. Never block scheduled runs.
$script:GeneratedPublishPaths = @(
    "ui_runner/templates/tickets_latest.json"
    "ui_runner/docs/tickets_latest.json"
    "ui_runner/data/tickets_latest.json"
    "mobile/www/tickets_latest.json"
    "ui_runner/templates/tickets_winrate_latest.json"
    "ui_runner/docs/tickets_winrate_latest.json"
    "ui_runner/data/tickets_winrate_latest.json"
    "mobile/www/tickets_winrate_latest.json"
    "ui_runner/templates/slate_latest.json"
    "mobile/www/slate_latest.json"
    "ui_runner/templates/pipeline_status.json"
    "mobile/www/pipeline_status.json"
    "ui_runner/templates/sport_breakdown.json"
    "ui_runner/docs/sport_breakdown.json"
    "mobile/www/sport_breakdown.json"
    "data/sport_breakdown.json"
    "ui_runner/templates/hot_cold_latest.json"
    "mobile/www/hot_cold_latest.json"
    "ui_runner/templates/prop_snapshot_latest.json"
    "mobile/www/prop_snapshot_latest.json"
)

function Write-PullHost {
    param([string]$Message, [string]$Color = "DarkGray")
    Write-Host "$Label $Message" -ForegroundColor $Color
}

function Get-GitDir {
    param([string]$Root)
    $raw = (git -C $Root rev-parse --git-dir 2>$null | Out-String).Trim()
    if (-not $raw) { return $null }
    if ([System.IO.Path]::IsPathRooted($raw)) { return $raw }
    return (Join-Path $Root ($raw -replace "/", [IO.Path]::DirectorySeparatorChar))
}

function Get-UnmergedPaths {
    param([string]$Root)
    $paths = @()
    $lines = @(git -C $Root ls-files -u 2>$null)
    foreach ($line in $lines) {
        if ([string]::IsNullOrWhiteSpace($line)) { continue }
        # format: <mode> <sha> <stage>\t<path>
        $tab = $line.IndexOf("`t")
        if ($tab -lt 0) { continue }
        $p = $line.Substring($tab + 1).Trim() -replace "\\", "/"
        if ($p -and ($paths -notcontains $p)) { $paths += $p }
    }
    return $paths
}

function Test-IsGeneratedPublishPath {
    param([string]$RelPath)
    $n = ($RelPath -replace "\\", "/").TrimStart("./")
    foreach ($g in $script:GeneratedPublishPaths) {
        if ($n -eq $g) { return $true }
        # basename match for mirrored copies
        if ([IO.Path]::GetFileName($n) -eq [IO.Path]::GetFileName($g) -and
            ($n -like "ui_runner/*" -or $n -like "mobile/*" -or $n -like "data/*")) {
            return $true
        }
    }
    return $false
}

function Reset-PathToHead {
    param([string]$Root, [string]$RelPath)
    $rel = $RelPath -replace "\\", "/"
    # Clear unmerged stages + restore HEAD version (or remove if absent on HEAD).
    git -C $Root restore --source=HEAD --staged --worktree -- $rel 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) {
        git -C $Root checkout HEAD -- $rel 2>&1 | Out-Null
    }
    if ($LASTEXITCODE -ne 0) {
        # File may be deleted on HEAD (UD). Drop from index + worktree.
        git -C $Root rm -f -- $rel 2>&1 | Out-Null
        $full = Join-Path $Root ($rel -replace "/", [IO.Path]::DirectorySeparatorChar)
        if (Test-Path -LiteralPath $full) {
            Remove-Item -LiteralPath $full -Force -ErrorAction SilentlyContinue
        }
    }
}

function Repair-RepoForScheduledPull {
    param([string]$Root)

    $gitDir = Get-GitDir -Root $Root
    if (-not $gitDir) {
        Write-PullHost "Not a git repo; skip repair." "Yellow"
        return 0
    }

    # Abort leftover in-progress ops. Generated conflicts after this are orphaned index junk.
    if (Test-Path -LiteralPath (Join-Path $gitDir "MERGE_HEAD")) {
        Write-PullHost "Aborting leftover merge..." "Yellow"
        git -C $Root merge --abort 2>&1 | ForEach-Object { Write-PullHost "  $_" }
    }
    if (Test-Path -LiteralPath (Join-Path $gitDir "CHERRY_PICK_HEAD")) {
        Write-PullHost "Aborting leftover cherry-pick..." "Yellow"
        git -C $Root cherry-pick --abort 2>&1 | ForEach-Object { Write-PullHost "  $_" }
    }
    if ((Test-Path -LiteralPath (Join-Path $gitDir "rebase-merge")) -or
        (Test-Path -LiteralPath (Join-Path $gitDir "rebase-apply"))) {
        Write-PullHost "Aborting leftover rebase..." "Yellow"
        git -C $Root rebase --abort 2>&1 | ForEach-Object { Write-PullHost "  $_" }
    }

    $unmerged = @(Get-UnmergedPaths -Root $Root)
    if ($unmerged.Count -eq 0) {
        return 0
    }

    Write-PullHost ("Found {0} unmerged path(s); clearing generated publish artifacts..." -f $unmerged.Count) "Yellow"
    $sourceConflicts = @()
    foreach ($p in $unmerged) {
        if (Test-IsGeneratedPublishPath -RelPath $p) {
            Write-PullHost "  reset generated: $p" "DarkYellow"
            Reset-PathToHead -Root $Root -RelPath $p
        }
        else {
            $sourceConflicts += $p
        }
    }

    $still = @(Get-UnmergedPaths -Root $Root)
    $stillGen = @($still | Where-Object { Test-IsGeneratedPublishPath -RelPath $_ })
    $stillSrc = @($still | Where-Object { -not (Test-IsGeneratedPublishPath -RelPath $_) })

    foreach ($p in $stillGen) {
        Write-PullHost "  force-clear generated: $p" "DarkYellow"
        # Nuclear clear of orphaned stages for this path
        git -C $Root update-index --force-remove -- $p 2>&1 | Out-Null
        git -C $Root checkout HEAD -- $p 2>&1 | Out-Null
        if ($LASTEXITCODE -ne 0) {
            Reset-PathToHead -Root $Root -RelPath $p
        }
    }

    $final = @(Get-UnmergedPaths -Root $Root)
    $finalSrc = @($final | Where-Object { -not (Test-IsGeneratedPublishPath -RelPath $_) })
    if ($finalSrc.Count -gt 0) {
        Write-PullHost "Real source conflicts remain (will not auto-destroy):" "Red"
        $finalSrc | Select-Object -First 15 | ForEach-Object { Write-PullHost "  $_" "Red" }
        return 2
    }

    # Any leftover generated-only junk: hard-reset those paths
    foreach ($p in $final) {
        Reset-PathToHead -Root $Root -RelPath $p
    }

    $check = @(Get-UnmergedPaths -Root $Root)
    if ($check.Count -gt 0) {
        Write-PullHost "WARNING: still unmerged after repair; attempting index refresh..." "Yellow"
        git -C $Root reset -q HEAD -- $check 2>&1 | Out-Null
        foreach ($p in $check) { Reset-PathToHead -Root $Root -RelPath $p }
    }

    $check2 = @(Get-UnmergedPaths -Root $Root)
    if ($check2.Count -gt 0) {
        Write-PullHost "FAILED to clear unmerged paths:" "Red"
        $check2 | ForEach-Object { Write-PullHost "  $_" "Red" }
        return 2
    }

    Write-PullHost "Unmerged publish artifacts cleared." "Green"
    return 0
}

# ---- main ----
if (-not $RepoRoot) {
    $RepoRoot = (Get-Location).Path
}
$RepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path
Set-Location $RepoRoot

$repairCode = Repair-RepoForScheduledPull -Root $RepoRoot
if ($repairCode -ne 0) {
    exit $repairCode
}

if ($SkipPull) {
    exit 0
}

if (-not $StashMessage) {
    $StashMessage = "proporacle-pre-pull-$(Get-Date -Format 'yyyyMMdd_HHmmss')"
}

Write-PullHost "Stashing local changes (if any)..." "Cyan"
$stashOut = @(git -C $RepoRoot stash push -u -m $StashMessage 2>&1)
$stashOut | ForEach-Object { Write-PullHost "  $_" }
$didStash = ($stashOut -join "`n") -notmatch "No local changes to save"

Write-PullHost "git pull --ff-only origin main..." "Cyan"
git -C $RepoRoot pull --ff-only origin main 2>&1 | ForEach-Object { Write-PullHost "  $_" }
$pullExit = $LASTEXITCODE

if ($pullExit -ne 0) {
    Write-PullHost "git pull failed (exit $pullExit)." "Yellow"
    if ($didStash) {
        Write-PullHost "Leaving pre-pull stash intact for manual recovery." "Yellow"
    }
    if ($ContinueOnPullFail) {
        Write-PullHost "Continuing with local tree (scheduled run must not abort on pull)." "Yellow"
        exit 0
    }
    exit $pullExit
}

if ($didStash) {
    Write-PullHost "Restoring stash..." "Cyan"
    git -C $RepoRoot stash pop 2>&1 | ForEach-Object { Write-PullHost "  stash pop: $_" }
    $popExit = $LASTEXITCODE
    $unmergedAfter = @(Get-UnmergedPaths -Root $RepoRoot)
    if ($popExit -ne 0 -or $unmergedAfter.Count -gt 0) {
        Write-PullHost "Stash pop conflicts — repairing generated paths..." "Yellow"
        $repair2 = Repair-RepoForScheduledPull -Root $RepoRoot
        $left = @(Get-UnmergedPaths -Root $RepoRoot)
        if ($repair2 -ne 0 -or $left.Count -gt 0) {
            # Last resort for scheduled: drop conflicted generated state to HEAD; keep stash.
            Write-PullHost "Resetting remaining conflicted paths to HEAD so the run can proceed..." "Yellow"
            foreach ($p in $left) {
                Reset-PathToHead -Root $RepoRoot -RelPath $p
            }
            $left2 = @(Get-UnmergedPaths -Root $RepoRoot)
            if ($left2.Count -gt 0) {
                Write-PullHost "Source conflicts after stash pop; stash kept. Abort." "Red"
                $left2 | ForEach-Object { Write-PullHost "  $_" "Red" }
                exit 2
            }
        }
        Write-PullHost "Stash conflicts cleared (stash entry may still exist — safe)." "Green"
    }
}

Write-PullHost "Repo ready for scheduled run." "Green"
exit 0
